#
# Copyright (c) 2016 Krzysztof Jusiak (krzysztof at jusiak dot net)
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
sudo: false
env:
  global:
  - secure: "TApi3LdRToyQgUkEAUpgV87gGCMaxgQIP+BNeFYGHSsy/mMfTACQkjlNZpm34HzQ83y8vs6bCAIw42gRvoWGB3HV5WIY7AEnCqMDkHSd/oQGjwg0tXznAO+A2cNTtE1uwBmDBAtgiN6BUiaJ8/xkTk/bzlS3X0pNK1rbe2UfJwGtwWhZbtO1z/eude1qc8iRd53rr3qfdv7snEoU910xap5ZRiOnlrOxpfEPfuA/Wln7+N/ZRkKoG0Qn1IiekrbZjJj7LwGCrZ9fuQBe5T1B6nZHbePw8W6oHX3kJ095V0Dbp+rjue3f7Mtu362WdJqDh65uZijENgUO+/y+3pNiGonEqOTgRvyssvjr4MaGlmtPjQ9MlmXd8CkZ6R+iOYYdPvAdMyRLKGHhar316BEer13p5dniITcO3LV9z4OnxMLyTUK6Je5viNIG+evFxBJ5VSHP38m394x6hBMm2/KAc56KQaRMr7Ycy6jIkrvGdeMmqf5D3WcMx8PgGo0GgFdRQ8jUrowy3NivYdPVc82ywoJn4JiNQlYfJU/M/QRZV3uSmscqTjO0HAKVaX8wafohbhwtJD7GIoUrdr19tNJ5K2+x/AK3gPBh+dzaXxxzoq1tvp90iSdUF40h90RSk4PEa93KAXyVUJ7HGWINdvWikkJWGa5q5d28hQPq6j6DLSE=" # GH_TOKEN
  - secure: "piiyYcJt9VXzHMgG4uUMe6kFA7iE8mC39/8AhlzJu2xwLeldEGlaHr+oi/2e0Ox/eM9saIR/9EoReSw8CRSZrU10/s4vKXS+TUfnWpAdPUM2goxlUcQ5JvR8ggiwkhJ2HE8lmpwqXF0nJNfIvFhmzIE+MIYO64f8QJviiN8PIoXGL9K67xqe/gex3qkYL4uz6/DgXMql3pYvX3thSVAj55Ujox8Vz3ykF3FoqWAlPAM17k/2fCyo95kdeHupawKRBeAOdxWK3wCtuNn3pyUAhJfJYi4FdJTJ+LAUnL/Pb3LpGOWTT+FGFDLS/rKS0JO/bpu2lxgiXpcQqoxVxvZmXeWDw0H67v5CImBmjb2Cgg+fLOwfNAx7XOhRIXsNRkPa+YmVLIPr4MRAIUFmX8FqljWIK3zvF6Kdabolw12lc48t0rK+QfBx5CRAI7pen7EIR3GnyV+vTylsuB5EPsvfe3BO9+C8DhZuUm6OtAg5ne/UAzr/zXq6hB9k/QNU3mtWBIn4D/5L6sufHCS8d5polClzkua2fUk20NEyZyhBQ3iFSNmXc3glmE7ZoEel+1bpKqrZo3IK1Ck97vKp2kJ7Ui3GK3fBhCwreq7sKwCX7hy/QW/RM7MtiyrsJdc8h6Tdp475LfSVhUwcRywv5zS6F5wJQZ7qBPxSs8ovV3gytgk=" # COVERALLS_REPO_TOKEN

branches:
  except:
    - gh-pages
    - benchmarks

matrix:
  fast_finish: true

  allow_failures:
    - env: CXX=clang++-3.9 MEMCHECK=VALGRIND

  include:
  - os: linux
    env: CHECK=ON CLANG_FORMAT=clang-format-3.8 CLANG_TIDY=clang-tidy-3.8
    addons:
      apt:
        packages: ["clang-format-3.8", "clang-tidy-3.8"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"]
  - os: linux
    env: DOCUMENTATION=ON
  - os: linux
    env: CXX=/usr/local/clang-3.4/bin/clang++ MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["clang-3.4", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.4"]
  - os: linux
    env: CXX=clang++-3.5 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["clang-3.5", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.5"]
  - os: linux
    env: CXX=clang++-3.6 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["clang-3.6", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.6"]
  - os: linux
    env: CXX=clang++-3.7 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["clang-3.7", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.7"]
  - os: linux
    env: CXX=clang++-3.8 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["clang-3.8", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"]
  - os: linux
    env: CXX=clang++-3.9 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["clang-3.9", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise"]
  - os: linux
    env: CXX=g++-5 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["g++-5", "libstdc++-5-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test"]
  - os: linux
    env: CXX=g++-6 MEMCHECK=VALGRIND
    addons:
      apt:
        packages: ["g++-6", "libstdc++-6-dev", "valgrind"]
        sources: ["ubuntu-toolchain-r-test"]
  - os: linux
    env: CXX=g++-6 GCOV=gcov-6 COVERAGE=GCOV
    addons:
      apt:
        packages: ["g++-6", "libstdc++-6-dev"]
        sources: ["ubuntu-toolchain-r-test"]
  - os: osx
    osx_image: xcode6.1
    env: CXX=clang++
  - os: osx
    osx_image: xcode6.4
    env: CXX=clang++
  - os: osx
    osx_image: xcode7
    env: CXX=clang++
  - os: osx
    osx_image: xcode7.1
    env: CXX=clang++
  - os: osx
    osx_image: xcode7.2
    env: CXX=clang++
  - os: osx
    osx_image: xcode7.3
    env: CXX=clang++
  - os: osx
    osx_image: xcode8
    env: CXX=clang++

before_install:
  - git config --global user.name "Continuous Integration"
  - git config --global user.email "kris@jusiak.net"
  - git config --global push.default simple

script:
  - if [ "${CXX}" != "" ] && [ "${COVERAGE}" == "" ]; then (travis_wait make test example); fi
  - if [ "${CXX}" != "" ] && [ "${COVERAGE}" != "" ]; then (travis_wait make test); fi
  - if [ "${CHECK}" != "" ]; then (travis_wait make check); fi
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${DOCUMENTATION}" != "" ]; then (
    pip install --user travis https://github.com/mkdocs/mkdocs/archive/b30f38fe299738e8ce614e53c3342cc8bef02b5b.zip --upgrade
    && git clone https://github.com/boost-experimental/sml && cd sml && rm -rf *
    && git checkout -b gh-pages -t origin/gh-pages && git reset --hard && cd ..
    && MKDOCS_THEME=boost-experimental MKDOCS_SITE=../sml make doc
    && MKDOCS_THEME=boost-classic MKDOCS_SITE=../sml/boost make doc readme
    && cd sml && git add -A . && git commit -am "doc update"
    && git push --force --quiet "https://${GH_TOKEN}@github.com/boost-experimental/sml.git"); fi

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${COVERAGE}" != "" ]; then (pip
    install --user travis requests[security] cpp-coveralls && coveralls -r . -b . --gcov /usr/bin/${GCOV}
    --repo-token "${COVERALLS_REPO_TOKEN}"); fi

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/860de502083214ed3d28
  on_success: change
  on_failure: always
  on_start: false

