image:
  - Visual Studio 2019

clone_folder: c:\projects\source

cache: c:\tools\vcpkg\installed

install:
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd c:\tools\vcpkg
  - vcpkg integrate install

build_script:
  - mkdir c:\projects\source\_build
  - cd c:\projects\source\_build
  - cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . 

test_script:
  - ctest -C Debug
  - ctest -C Debug --rerun-failed --output-on-failure
