image:
  - Visual Studio 2019

# environment:
#   matrix:
#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#       CMAKE_GENERATOR: Visual Studio 15
#     - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#       CMAKE_GENERATOR: Visual Studio 16

clone_folder: c:\projects\source

cache: c:\tools\vcpkg\installed

install:
  - cd c:\tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
  - vcpkg install boost-geometry:x64-windows
  - vcpkg install boost-math:x64-windows
  - vcpkg install boost-outcome:x64-windows
  - vcpkg install boost-ublas:x64-windows
  - vcpkg install catch2:x64-windows
  - vcpkg install glm:x64-windows
  - vcpkg install nlohmann-json:x64-windows
  - cd c:\tools\vcpkg
  - vcpkg integrate install

build_script:
  - cmd: >-
      mkdir c:\projects\source\build
      cd c:\projects\source\build
      cmake -G "Visual Studio 16" -A x64 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
      cmake --build . --config "Debug"

test_script:
  - cmd: ctest -C Debug
