language: cpp
sudo: required
matrix:
  include:
  - os: linux
    env: COMPILER=g++-6
    addons:
      apt:
        packages:
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
  - os: linux
    env: COMPILER=g++-7
    addons:
      apt:
        packages:
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
before_install:
- export CXX="${COMPILER}"
- sudo apt-get -qq update
- sudo apt-get install -y catch
- sudo apt-get install -y libboost-dev
install: 
before_script:
- uname -a
script:
- mkdir -p _build && cd _build
- cmake ..
- cmake --build . --config Release -- -j4
- ctest
- make install
after_success:
## - cpack -G DEB
before_deploy:
  # - git fetch --tags
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: 86124491218dcd75ac73c5a4b76bbd50eb445a27
  ## todo 
  file: sec21-app1-1.2.3-x64.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
after_deploy: 
after_script:
- echo "Deploying build $TRAVIS_BUILD_NUMBER"
notifications:
  irc:
    channels:
    - chat.freenode.net#my-channel
    - chat.freenode.net#some-other-channel
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
