dist: trusty
language: cpp

matrix:
  fast_finish: true

  include:
#  - os: linux
#    env: COMPILER=clang++-3.5
#    addons:
#      apt:
#        packages: ["clang++-3.5"]
 #       sources: ['llvm-toolchain-precise-3.5', "ubuntu-toolchain-r-test"]

  - os: linux
    env: COMPILER=g++-5
    addons:
      apt:
        packages: ["g++-5"]
        sources: ["ubuntu-toolchain-r-test"]

before_script:

install:
  - export CXX="${COMPILER}"

script:
  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - mkdir -p build && cd build
  - cmake .. && cmake --build . --config Release -- -j4
  - ctest
  - cd ..

