language: cpp
dist: bionic

matrix:
  include:
  - os: linux
    env: COMPILER=g++-9
    addons:
      apt:
        update: true
        sources:
          #- sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
          #- libboost-dev
  - os: linux
    env: COMPILER=g++-10
    addons:
      apt:
        update: true
        sources:
        #   #- sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - g++-10
          #- libboost-dev
  # - os: linux
  #   env: COMPILER=clang++-9.0
  #   addons:
  #     apt:
  #       packages:
  #       - clang-9.0
  #       sources:
  #       - llvm-toolchain-bionic-9
  # - os: linux
  #   env: COMPILER=clang++-10.0
  #   addons:
  #     apt:
  #       packages:
  #       - clang-10.0
  #       sources:
  #       - llvm-toolchain-bionic-10

before_install:
- export CXX="${COMPILER}"
- sudo apt-get -qq update
- sudo apt-get -y install git
- git clone https://github.com/Microsoft/vcpkg.git
- cd vcpkg
- sh bootstrap-vcpkg.sh
- ./vcpkg install boost-mp11
- ./vcpkg install boost-math
- ./vcpkg install boost-qvm
- ./vcpkg install boost-outcome
- ./vcpkg install boost-ublas
- ./vcpkg install boost-program-options
- ./vcpkg install catch2
- ./vcpkg install glm
- ./vcpkg install nlohmann-json
- ./vcpkg install spdlog
- ./vcpkg install sdl2
- ./vcpkg install sdl2-image
# - ./vcpkg install glew
- ./vcpkg install imgui
- ./vcpkg install entt
- ./vcpkg install assimp
- ./vcpkg install freetype
- cd ..

before_script:
- uname -a

script:
- mkdir -p _build && cd _build
- cmake -DENABLE_COVERAGE:BOOL=FALSE -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
- cmake --build . -- -j4
- ctest -j2

branches:
  only:
  - master
  - "/^v\\d+\\./"

# after_script:
# after_success:
# before_deploy:
# deploy:
# after_deploy: 

notifications:
  irc:
    channels:
    - chat.freenode.net#sec21
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
