language:
  cpp

matrix:
  fast_finish: true

  include:
#  - os: linux
#    env: COMPILER=clang++-3.5
#    addons:
#      apt:
#        packages: ["clang++-3.5"]
 #       sources: ['llvm-toolchain-precise-3.5', "ubuntu-toolchain-r-test"]

  - os: linux
    env: COMPILER=g++-5
    addons:
      apt:
        packages: ["g++-5"]
        sources: ["ubuntu-toolchain-r-test"]

before_script:
  #- echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main universe restricted multiverse"
  #- sudo apt-get update -qq
  #- sudo apt-get -qq install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev
  #- sudo apt-get install -y emscripten

install:
  - export CXX="${COMPILER}"

script:
  - if [ "${CXX}" != "" ]; then (travis_wait mkdir build && cd build && cmake .. && cmake --build . && test); fi

  # todo: build tests and run it
  # todo: build with emcc

# after_success:
  # todo: push emcc result to webhost

notifications:
  email:
    - miller.michael@gmx.de
