language: cpp
sudo: required
matrix:
  include:
  - os: linux
    env: COMPILER=g++-6
    addons:
      apt:
        packages:
        - g++-6
        sources:
        - ubuntu-toolchain-r-test
  - os: linux
    env: COMPILER=g++-7
    addons:
      apt:
        packages:
        - g++-7
        sources:
        - ubuntu-toolchain-r-test
before_install:
- export CXX="${COMPILER}"
- sudo apt-get -qq update
- sudo apt-get install -y catch
- sudo apt-get install -y boost
install: 
before_script:
- uname -a
script:
- mkdir -p _build && cd _build
- cmake ..
- cmake --build . --config Release -- -j4
- ctest
after_success:
## - cpack -G DEB
before_deploy:
- git fetch --tags
deploy:
  ## TODO
  ## provider: releases
  ## user: 
  ## file: foo_bin1-1.0.0-Linux.deb
after_deploy: 
after_script:
- echo "Deploying build $TRAVIS_BUILD_NUMBER"
notifications:
  irc:
    channels:
    - chat.freenode.net#my-channel
    - chat.freenode.net#some-other-channel
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
