language: cpp
dist: bionic

matrix:
  include:
  - os: linux
    env: COMPILER=g++-8
    addons:
      apt:
        update: true
        sources:
          #- sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          #- libboost-dev
  - os: linux
    env: COMPILER=g++-9
    addons:
      apt:
        update: true
        sources:
          #- sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - g++-9
          #- libboost-dev
  - os: linux
    env: COMPILER=g++-10
    addons:
      apt:
        update: true
        sources:
          #- sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - g++-10
          #- libboost-dev
  # - os: linux
  #   env: COMPILER=clang++-9.0
  #   addons:
  #     apt:
  #       packages:
  #       - clang-9.0
  #       sources:
  #       - llvm-toolchain-bionic-9
  # - os: linux
  #   env: COMPILER=clang++-10.0
  #   addons:
  #     apt:
  #       packages:
  #       - clang-10.0
  #       sources:
  #       - llvm-toolchain-bionic-10

before_install:
- export CXX="${COMPILER}"
- sudo apt-get -qq update

before_script:
- uname -a

script:
- mkdir -p _build && cd _build
- cmake .. -DENABLE_COVERAGE:BOOL=FALSE
- travis_wait 30 cmake --build . -- -j4
- ctest -j2

branches:
  only:
  - master
  - "/^v\\d+\\./"

# after_script:
# after_success:
# before_deploy:
# deploy:
# after_deploy: 

notifications:
  irc:
    channels:
    - chat.freenode.net#sec21
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
