name: GCC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 12, 13, 14 ]
        config: [ Debug, Release ]

    steps:
      - uses: actions/checkout@master

      - name: Install compiler
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install gcc-${{matrix.version}} g++-${{matrix.version}}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{matrix.version}} 110 --slave /usr/bin/g++ g++ /usr/bin/g++-${{matrix.version}} --slave /usr/bin/gcov gcov /usr/bin/gcov-${{matrix.version}}
          g++ --version

      - name: Setup system
        run: |
          sudo apt install -y libboost-all-dev

      - name: Install Dependencies
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          git clone https://github.com/Microsoft/vcpkg.git 
          cd vcpkg
          ./bootstrap-vcpkg.sh

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}} -DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config ${{matrix.config}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest --build-config ${{matrix.config}} --rerun-failed --output-on-failure

