name: MSVC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: ${{runner.workspace}}
      run: |
        git clone https://github.com/Microsoft/vcpkg.git 
        cd vcpkg
        bootstrap-vcpkg.bat
        vcpkg install boost-core:x64-windows
        vcpkg install boost-function-types:x64-windows 
        vcpkg install boost-hana:x64-windows
        vcpkg install boost-math:x64-windows
        vcpkg install boost-qvm:x64-windows
        vcpkg install boost-range:x64-windows
        vcpkg install boost-mp11:x64-windows
        vcpkg install boost-algorithm:x64-windows
        vcpkg install boost-date-time:x64-windows
        vcpkg install catch2:x64-windows
        vcpkg install fmt:x64-windows
        vcpkg install nlohmann-json:x64-windows
        vcpkg integrate install

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}} -DCMAKE_TOOLCHAIN_FILE=D:/a/sec21/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.config}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --build-config ${{matrix.config}}
